services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                VITE_REVERB_APP_KEY: ${REVERB_APP_KEY}
                VITE_REVERB_HOST: ${VITE_REVERB_HOST}
                VITE_REVERB_PORT: ${VITE_REVERB_PORT}
                VITE_REVERB_SCHEME: ${VITE_REVERB_SCHEME}
                VITE_REVERB_PATH: ${VITE_REVERB_PATH}
        image: '365home/app:latest'
        restart: unless-stopped
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - './storage:/var/www/html/storage'
        env_file: .env
        dns:
            - 8.8.8.8
            - 8.8.4.4
        networks:
            - app
            - mariadb_default
        depends_on:
            - redis

    redis:
        image: redis:7-alpine
        restart: unless-stopped
        networks:
            - app

    reverb:
        image: '365home/app:latest'
        restart: unless-stopped
        command: php artisan reverb:start --host=0.0.0.0 --port=6001
        ports:
            - '6001:6001'
        env_file: .env
        networks:
            - app
            - mariadb_default
        depends_on:
            - redis

networks:
    app:
        driver: bridge
    mariadb_default:
        external: true
