<?php

// DANH SÁCH NGÂN HÀNG cho ô chọn ngân hàng (form đăng ký đối tác, tài chính đối tác, API /api/v2/banks).
// Khoá = mã ngân hàng; bin = mã BIN theo chuẩn VietQR/NAPAS. Tên hiển thị lưu vào hồ sơ đối tác là short_name.
// Thêm/sửa ngân hàng tại đây (không nhập tay tên ngân hàng).
return [
    'list' => [
        'VCB'   => ['short_name' => 'Vietcombank',  'name' => 'Ngân hàng TMCP Ngoại thương Việt Nam',              'bin' => '970436'],
        'CTG'   => ['short_name' => 'VietinBank',   'name' => 'Ngân hàng TMCP Công thương Việt Nam',               'bin' => '970415'],
        'BIDV'  => ['short_name' => 'BIDV',         'name' => 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam',      'bin' => '970418'],
        'AGB'   => ['short_name' => 'Agribank',     'name' => 'Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam', 'bin' => '970405'],
        'TCB'   => ['short_name' => 'Techcombank',  'name' => 'Ngân hàng TMCP Kỹ thương Việt Nam',                 'bin' => '970407'],
        'MB'    => ['short_name' => 'MB Bank',      'name' => 'Ngân hàng TMCP Quân đội',                           'bin' => '970422'],
        'ACB'   => ['short_name' => 'ACB',          'name' => 'Ngân hàng TMCP Á Châu',                             'bin' => '970416'],
        'VPB'   => ['short_name' => 'VPBank',       'name' => 'Ngân hàng TMCP Việt Nam Thịnh Vượng',               'bin' => '970432'],
        'TPB'   => ['short_name' => 'TPBank',       'name' => 'Ngân hàng TMCP Tiên Phong',                         'bin' => '970423'],
        'STB'   => ['short_name' => 'Sacombank',    'name' => 'Ngân hàng TMCP Sài Gòn Thương Tín',                 'bin' => '970403'],
        'HDB'   => ['short_name' => 'HDBank',       'name' => 'Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh',   'bin' => '970437'],
        'VIB'   => ['short_name' => 'VIB',          'name' => 'Ngân hàng TMCP Quốc tế Việt Nam',                   'bin' => '970441'],
        'SHB'   => ['short_name' => 'SHB',          'name' => 'Ngân hàng TMCP Sài Gòn - Hà Nội',                   'bin' => '970443'],
        'MSB'   => ['short_name' => 'MSB',          'name' => 'Ngân hàng TMCP Hàng Hải Việt Nam',                  'bin' => '970426'],
        'OCB'   => ['short_name' => 'OCB',          'name' => 'Ngân hàng TMCP Phương Đông',                        'bin' => '970448'],
        'SEAB'  => ['short_name' => 'SeABank',      'name' => 'Ngân hàng TMCP Đông Nam Á',                         'bin' => '970440'],
        'LPB'   => ['short_name' => 'LPBank',       'name' => 'Ngân hàng TMCP Lộc Phát Việt Nam',                  'bin' => '970449'],
        'EIB'   => ['short_name' => 'Eximbank',     'name' => 'Ngân hàng TMCP Xuất Nhập khẩu Việt Nam',            'bin' => '970431'],
        'SCB'   => ['short_name' => 'SCB',          'name' => 'Ngân hàng TMCP Sài Gòn',                            'bin' => '970429'],
        'ABB'   => ['short_name' => 'ABBANK',       'name' => 'Ngân hàng TMCP An Bình',                            'bin' => '970425'],
        'NAB'   => ['short_name' => 'Nam A Bank',   'name' => 'Ngân hàng TMCP Nam Á',                              'bin' => '970428'],
        'BAB'   => ['short_name' => 'Bac A Bank',   'name' => 'Ngân hàng TMCP Bắc Á',                              'bin' => '970409'],
        'NCB'   => ['short_name' => 'NCB',          'name' => 'Ngân hàng TMCP Quốc Dân',                           'bin' => '970419'],
        'PVCB'  => ['short_name' => 'PVcomBank',    'name' => 'Ngân hàng TMCP Đại chúng Việt Nam',                 'bin' => '970412'],
        'VAB'   => ['short_name' => 'VietABank',    'name' => 'Ngân hàng TMCP Việt Á',                             'bin' => '970427'],
        'BVB'   => ['short_name' => 'BaoViet Bank', 'name' => 'Ngân hàng TMCP Bảo Việt',                           'bin' => '970438'],
        'KLB'   => ['short_name' => 'KienlongBank', 'name' => 'Ngân hàng TMCP Kiên Long',                          'bin' => '970452'],
        'VCCB'  => ['short_name' => 'Viet Capital Bank', 'name' => 'Ngân hàng TMCP Bản Việt',                      'bin' => '970454'],
        'SGB'   => ['short_name' => 'Saigonbank',   'name' => 'Ngân hàng TMCP Sài Gòn Công Thương',                'bin' => '970400'],
        'PGB'   => ['short_name' => 'PGBank',       'name' => 'Ngân hàng TMCP Thịnh vượng và Phát triển',          'bin' => '970430'],
        'CBB'   => ['short_name' => 'CBBank',       'name' => 'Ngân hàng Thương mại TNHH MTV Xây dựng Việt Nam',   'bin' => '970444'],
        'COOP'  => ['short_name' => 'Co-opBank',    'name' => 'Ngân hàng Hợp tác xã Việt Nam',                     'bin' => '970446'],
        'SHBVN' => ['short_name' => 'Shinhan Bank', 'name' => 'Ngân hàng TNHH MTV Shinhan Việt Nam',               'bin' => '970424'],
        'WOORI' => ['short_name' => 'Woori Bank',   'name' => 'Ngân hàng TNHH MTV Woori Việt Nam',                 'bin' => '970457'],
        'HSBC'  => ['short_name' => 'HSBC',         'name' => 'Ngân hàng TNHH MTV HSBC (Việt Nam)',                'bin' => '458761'],
        'UOB'   => ['short_name' => 'UOB',          'name' => 'Ngân hàng TNHH MTV United Overseas Bank (Việt Nam)', 'bin' => '970458'],
        'PBVN'  => ['short_name' => 'Public Bank',  'name' => 'Ngân hàng TNHH MTV Public Việt Nam',                'bin' => '970439'],
        'CIMB'  => ['short_name' => 'CIMB',         'name' => 'Ngân hàng TNHH MTV CIMB Việt Nam',                  'bin' => '422589'],
        'SCVN'  => ['short_name' => 'Standard Chartered', 'name' => 'Ngân hàng TNHH MTV Standard Chartered Bank Việt Nam', 'bin' => '970410'],
        'CAKE'  => ['short_name' => 'CAKE',         'name' => 'Ngân hàng số CAKE by VPBank',                       'bin' => '546034'],
        'UBANK' => ['short_name' => 'Ubank',        'name' => 'Ngân hàng số Ubank by VPBank',                      'bin' => '546035'],
    ],
];
